networks:
  bench-net:

volumes:
  hdfs-nn:
  hdfs-dn:
  spark-history:

services:
  # ==== HDFS (официальные Apache Hadoop образы) ====
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    hostname: namenode
    user: "0:0"
    networks: [bench-net]
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hdfs-nn:/var/lib/hadoop-hdfs
      - ./hadoop-conf:/opt/hadoop/etc/hadoop:ro
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - PATH=/opt/hadoop/bin:/opt/hadoop/sbin:$PATH
      - ENSURE_NAMENODE_DIR=/var/lib/hadoop-hdfs/name
    command: ["hdfs","namenode"]
    restart: unless-stopped

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    hostname: datanode
    user: "0:0"
    depends_on: [namenode]
    networks: [bench-net]
    ports:
      - "9864:9864"
    volumes:
      - hdfs-dn:/var/lib/hadoop-hdfs
      - ./hadoop-conf:/opt/hadoop/etc/hadoop:ro
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - PATH=/opt/hadoop/bin:/opt/hadoop/sbin:$PATH
    command: ["hdfs","datanode"]
    restart: unless-stopped

  # ==== Spark кластер (Bitnami) ====
  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"                   # Spark Master UI
      - "7077:7077"                   # Spark Master RPC
    volumes:
      - spark-history:/opt/spark/history
    networks: [bench-net]
    restart: unless-stopped

  spark-worker-1:
    image: bitnami/spark:3.3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    depends_on: [spark-master]
    networks: [bench-net]
    restart: unless-stopped

  spark-worker-2:
    image: bitnami/spark:3.3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
    depends_on: [spark-master]
    networks: [bench-net]
    restart: unless-stopped

  # ==== Spark History Server (уже ОК) ====
  spark-history:
    image: bitnami/spark:3.3
    container_name: spark-history
    depends_on: [spark-master]
    networks: [bench-net]
    ports:
      - "18080:18080"
    volumes:
      - spark-history:/opt/spark/history
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/opt/spark/history -Dspark.history.ui.port=18080
    command: ["bash","-lc","mkdir -p /opt/spark/history && /opt/bitnami/spark/sbin/start-history-server.sh && sleep infinity"]
    restart: unless-stopped

  # ==== HiBench ====
  hibench:
    build:
      context: ./hibench
      dockerfile: Dockerfile
    container_name: hibench
    depends_on: [namenode, datanode, spark-master]
    networks: [bench-net]
    volumes:
      - spark-history:/opt/spark/history   # чтобы event logs видел History UI
    # держим контейнер запущенным и готовы выполнять команды внутрь
    command: ["bash","-lc","sleep infinity"]
    restart: unless-stopped

