global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:7071']
  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:7071']
