"""
Генерирует случайных кандидатов конфигураций Spark в пределах топологии и ограничений.

Параметрическое пространство совпадает с collect_hibench_data.sh:
    executor_cores:          1 .. min(worker_cores, 8)
    executor_memory_mb:      1g .. min(worker_mem_gb, 8)g  (шаг 1g = 1024 MB)
    executor_instances:      1 .. min(workers, 8)
    driver_cores:            1 .. 4
    driver_memory_mb:        1g .. 4g
    maxSizeInFlight_mb:      48, 56, 64, 72, 80, 88, 96
    shuffle_compress:        0 | 1
    spill_compress:          0 | 1
    shuffle_file_buffer_kb:  32, 48, 64, 80, 96, 112, 128
    broadcast_block_mb:      4, 6, 8 .. 24  (шаг 2)
    broadcast_compress:      0 | 1
    memory_fraction:         0.3 .. 0.8  (шаг 0.1)
    memory_storageFraction:  0.3 .. 0.8  (шаг 0.1)
    rpc_message_maxSize:     128, 160, 192, 224, 256
    rdd_compress:            0 | 1
    io_codec:                lz4 | snappy
"""

import random
from typing import Optional


_INFLIGHT_MB = [48, 56, 64, 72, 80, 88, 96]
_FILE_BUF_KB = [32, 48, 64, 80, 96, 112, 128]
_BCAST_BLOCK_MB = list(range(4, 25, 2))
_MEM_FRAC = [round(0.1 * i, 1) for i in range(3, 9)]   # 0.3 .. 0.8
_RPC_MAX = [128, 160, 192, 224, 256]
_CODECS = ["lz4", "snappy"]
_DRIVER_MEM_MB = [1024, 2048, 3072, 4096]

_STATIC_ALLOWED_VALUES = {
    "driver_cores": list(range(1, 5)),
    "driver_memory_mb": _DRIVER_MEM_MB,
    "memory_fraction": _MEM_FRAC,
    "memory_storageFraction": _MEM_FRAC,
    "shuffle_compress": [0, 1],
    "spill_compress": [0, 1],
    "shuffle_file_buffer_kb": _FILE_BUF_KB,
    "broadcast_block_mb": _BCAST_BLOCK_MB,
    "broadcast_compress": [0, 1],
    "maxSizeInFlight_mb": _INFLIGHT_MB,
    "rpc_message_maxSize": _RPC_MAX,
    "rdd_compress": [0, 1],
}


def _warn_if_not_in_grid(cfg: dict, name: str, allowed: list) -> list[str]:
    if name not in cfg or cfg[name] in allowed:
        return []
    return [
        f"{name}={cfg[name]} is outside sampled design grid {allowed}; "
        "prediction may be unreliable"
    ]


def config_distribution_warnings(
    cfg: dict,
    topology_workers: int,
    topology_worker_cores: int,
    topology_worker_mem_gb: int,
) -> list[str]:
    """
    Warn when a user-supplied config leaves the sampled design space used by
    collect_hibench_data.sh. Recommendations generated by this module should
    normally not trigger these warnings.
    """
    warnings: list[str] = []

    dynamic_allowed = {
        "executor_cores": list(range(1, min(topology_worker_cores, 8) + 1)),
        "executor_memory_mb": list(range(1024, min(topology_worker_mem_gb, 8) * 1024 + 1, 1024)),
        "executor_instances": list(range(1, min(topology_workers, 8) + 1)),
    }
    for name, allowed in {**dynamic_allowed, **_STATIC_ALLOWED_VALUES}.items():
        warnings.extend(_warn_if_not_in_grid(cfg, name, allowed))

    codec = cfg.get("io_codec")
    if codec not in _CODECS:
        warnings.append(
            f"io_codec={codec!r} was not present in the sampled design grid {_CODECS}; "
            "prediction may be unreliable"
        )

    return warnings


def _clamp(val: int, lo: int, hi: int) -> int:
    return max(lo, min(hi, val))


def generate_candidates(
    topology_workers: int,
    topology_worker_cores: int,
    topology_worker_mem_gb: int,
    profile: str,
    n: int = 200,
    constraints: Optional[dict] = None,
    rng_seed: Optional[int] = None,
) -> list[dict]:
    """
    Возвращает список из n случайных конфигов.
    constraints — словарь с max_executor_cores / max_executor_memory_mb / max_executor_instances.
    """
    rng = random.Random(rng_seed) if rng_seed is not None else random

    con = constraints or {}

    max_ec = _clamp(con.get("max_executor_cores", 8), 1, min(topology_worker_cores, 8))
    max_em_gb = min(topology_worker_mem_gb, 8)
    max_em_mb = con.get("max_executor_memory_mb", max_em_gb * 1024)
    # Выравниваем до кратного 1g
    max_em_mb = _clamp((max_em_mb // 1024) * 1024, 1024, max_em_gb * 1024)
    max_ei = _clamp(con.get("max_executor_instances", 8), 1, min(topology_workers, 8))

    em_choices_mb = list(range(1024, max_em_mb + 1, 1024)) or [1024]
    ec_range = list(range(1, max_ec + 1))
    ei_range = list(range(1, max_ei + 1))
    driver_cores_range = list(range(1, 5))

    candidates = []
    for _ in range(n):
        ec = rng.choice(ec_range)
        em = rng.choice(em_choices_mb)
        ei = rng.choice(ei_range)
        dc = rng.choice(driver_cores_range)
        dm = rng.choice(_DRIVER_MEM_MB)
        mf = rng.choice(_MEM_FRAC)
        msf = rng.choice(_MEM_FRAC)
        candidates.append({
            "topology_workers": topology_workers,
            "topology_worker_cores": topology_worker_cores,
            "topology_worker_mem_gb": topology_worker_mem_gb,
            "profile": profile,
            "executor_cores": ec,
            "executor_memory_mb": em,
            "executor_instances": ei,
            "driver_cores": dc,
            "driver_memory_mb": dm,
            "memory_fraction": mf,
            "memory_storageFraction": msf,
            "shuffle_compress": rng.randint(0, 1),
            "spill_compress": rng.randint(0, 1),
            "shuffle_file_buffer_kb": rng.choice(_FILE_BUF_KB),
            "broadcast_block_mb": rng.choice(_BCAST_BLOCK_MB),
            "broadcast_compress": rng.randint(0, 1),
            "maxSizeInFlight_mb": rng.choice(_INFLIGHT_MB),
            "rpc_message_maxSize": rng.choice(_RPC_MAX),
            "rdd_compress": rng.randint(0, 1),
            "io_codec": rng.choice(_CODECS),
        })
    return candidates
